print("=" * 55)
print("IZVJEŠTAJ O ISTRAZI — Slučaj Dr. Emina Softić")
print("=" * 55)
print(f"Počinilac: Emir Begović (42), poslovni partner")
print(f"Motiv: Dugovi od -42,600 KM + polica životnog")
print(f"       osiguranja na žrtvu (korisnik: Emir)")
print(f"Dokaz 1: Pristupna kartica — ušao 18:45,")
print(f"         izašao 21:10. Jedini osumnjičeni u")
print(f"         zgradi tokom ubistva (19:30-20:30).")
print(f"Dokaz 2: Svjedok vidio visokog muškarca, tamna")
print(f"         kosa (188cm, crna) kako izlazi iz")
print(f"         kancelarije 301 u 20:15, uznemiren.")
print(f"Dokaz 3: U 20:20 zvao nepoznat broj 066999000")
print(f"         (45s). Ponovo u 22:00 (30s).")
print(f"Dokaz 4: groupby().sum() = -42,600 KM duga.")
print(f"         Polica osiguranja: korisnik u slučaju")
print(f"         smrti žrtve je Emir Begović.")
print("=" * 55)